[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "tlsotp"
version = "0.2.0"
description = "Time, Location, and Secret-based OTP generation library"
readme = "README.md"
requires-python = ">=3.8"

license = { file = "LICENSE" }

authors = [
    { name = "ASH-SuperUser" }
]

keywords = [
    "otp",
    "hmac",
    "security",
    "authentication",
    "cryptography",
    "tlsotp",
    "two-factor",
    "2fa",
    "time-based",
    "location-based"
]

classifiers = [
    # Status
    "Development Status :: 5 - Production/Stable",

    # Audience
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",

    # Topic
    "Topic :: Security",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",

    # License
    "License :: OSI Approved :: Apache Software License",

    # Python versions
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    # Implementations
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",

    # OS support
    "Operating System :: OS Independent",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: MacOS",

    # Extra metadata
    "Natural Language :: English",
    "Typing :: Typed"
]

dependencies = []

[project.optional-dependencies]
dev = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-autorefs",
    "pytest",
    "pytest-cov",
    "hypothesis",
    "ruff",
    "mypy",
    "griffe",
]
# dev = [
#     "pytest",
#     "hypothesis"
# ]

[project.urls]
Homepage = "https://github.com/ASH-SuperUser/tlsotp"
Repository = "https://github.com/ASH-SuperUser/tlsotp"
Issues = "https://github.com/ASH-SuperUser/tlsotp/issues"


# [tool.hatch.build.targets.wheel]
# packages = ["src/tlsotp"]


# [tool.hatch.metadata]
# license-files = ["LICENSE"]


# [tool.pytest.ini_options]
# pythonpath = ["src"]



# [tool.hatch.build]
# sources = ["src"]

# [tool.hatch.build.targets.wheel]
# packages = ["tlsotp"]


[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["tlsotp"]

[tool.hatch.metadata]
license-files = ["LICENSE"]

[tool.pytest.ini_options]
pythonpath = ["src"]
